//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class customMade
    {
        public int id { get; set; }
        public int uid { get; set; }
        public System.DateTime cTime { get; set; }
        public int jk { get; set; }
        public int xw { get; set; }
        public int yw { get; set; }
        public int tw { get; set; }
        public int xc { get; set; }
        public int qc { get; set; }
    }
}
